{{- if .Values.caSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caSecret.name }}
  labels:
    {{- include "swg.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.caSecret.caCrt | quote }}
  ca.key: {{ .Values.caSecret.caKey | quote }}
{{- end }}
